theme: jekyll-theme-leap-day
title: Result Library for Java
description: A Java library to handle success and failure without exceptions
current_version: 0.3.0.3
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
